on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:

  # Abort if the code isn't formatted according to rustfmt standards from nightly.
  fmt:
    name: Rustfmt
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      # Work around https://github.com/actions/cache/issues/133#issuecomment-599102035
      - run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/
        name: Fix perms on .cargo so we can restore the cache.
      - name: Cache cargo
        uses: actions/cache@v1
        with:
          path: ~/.cargo/
          key: ${{ github.job }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  # Build on all the architectures we intend to support, including cross compiled ones.
  build:
    name: Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            target: aarch64-linux-android # Android x64
          - os: ubuntu-18.04
            target: x86_64-unknown-linux-musl # Alpine Linux x86_64
          - os: ubuntu-18.04
            target: wasm32-unknown-unknown
          - os: macos-10.15
            target: aarch64-apple-ios
          - os: macos-10.15
            target: x86_64-apple-darwin # 64-bit OSX
          - os: windows-2019
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v2
      # Work around https://github.com/actions/cache/issues/133#issuecomment-599102035
      - run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/
        name: Fix perms on .cargo so we can restore the cache.
        if: "!contains(runner.os, 'windows')"
      - name: Cache cargo
        uses: actions/cache@v1
        with:
          path: ~/.cargo/
          key: ${{ github.job }}-${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ github.job }}-${{ runner.os }}-${{ matrix.target }}-target-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

  # Run the tests on only one architecture, against various Rust versions.
  test:
    name: Test Suite
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - 1.38.0 #MSRV
    steps:
      - uses: actions/checkout@v2
      # Work around https://github.com/actions/cache/issues/133#issuecomment-599102035
      - run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/
        name: Fix perms on .cargo so we can restore the cache.
      - name: Cache cargo
        uses: actions/cache@v1
        with:
          path: ~/.cargo/
          key: ${{ github.job }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ matrix.rust }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ github.job }}-${{ runner.os }}-target-${{ hashFiles('**/Cargo.toml') }}-${{ matrix.rust }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
