on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:

  # Build on all the architectures we intend to support, including cross compiled ones.
  build:
    name: Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            target: aarch64-linux-android # Android x64
          - os: ubuntu-18.04
            target: x86_64-unknown-linux-musl # Alpine Linux x86_64
          - os: ubuntu-18.04
            target: wasm32-unknown-unknown
          - os: macos-10.15
            target: aarch64-apple-ios
          - os: macos-10.15
            target: x86_64-apple-darwin # 64-bit OSX
          - os: windows-2019
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

  # Run the tests on only one architecture, against various Rust versions.
  test:
    name: Test Suite
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - 1.38.0 #MSRV
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  # Benchmark current against the base revision. Base is the previous rev, if we're merging to master; or base is master if this is
  # a PR.
  bench:
    name: Bench compare
    runs-on: ubuntu-18.04
    steps:
      - name: Find base revision
        id: base
        run: |
          if [ "${{ github.base_ref }}" != "" ] ; then
            BASE="${{ github.base_ref }}"
          else
            BASE=$(git rev-parse master@{1})
          fi
          echo "::set-output name=base::${BASE}"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: critcmp
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: bench
          args: -- --save-baseline current
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.base.outputs.base }}
          clean: 'false'
      - uses: actions-rs/cargo@v1
        with:
          command: bench
          args: -- --save-baseline base
      - name: Compare benchmarks
        run: |
          if ! critcmp base current -t 10 ; then
            echo "# Benchmark blew big budget! Bad!" > comment.md
          fi
          echo "Benchmark results comparing with base (${{ steps.base.outputs.base }}):" >> comment.md
          echo "```" >> comment.md
          critcmp base current -t 2 >> comment.md || true
          echo "```" >> comment.md
      - name: Store benchmark results
        uses: actions/upload-artifact@v1
        with:
          name: bench-results
          path: comment.md

  # Abort if the code isn't formatted according to rustfmt standards from nightly.
  fmt:
    name: Rustfmt
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  # Add a comment to the PR with benchmark results. Only if everything else passed, and this is a PR.
  bench_results:
    needs:
      - bench
      - build
      - fmt
      - test
    if: github.base_ref != ''
    name: Upload benchmark results
    runs-on: ubuntu-18.04
    steps:
      - name: Retrieve benchmark results
        uses: actions/download-artifact@v1
        with:
          name: bench-results
      - uses: harupy/comment-on-pr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: bench-results/comment.md
