name: Security Audit
on:
  schedule:
    - cron: "0 8 * * *" # 8AM UTC, 3PM MST
jobs:
  audit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
